name: audioset_tensorflow
dependencies:
    - python=3.6
    - numpy
    - scipy
    - matplotlib
    - h5py
    - future
    - cudnn=7.1.2
    - cudatoolkit=9
    - ipython
    - scikit-learn
    - pip:
        - tensorflow-gpu
        - keras
