#!/bin/bash
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 1024 --dropout_rate 0.5 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-2 --hidden_units 1024 --dropout_rate 0.5 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-1 --hidden_units 1024 --dropout_rate 0.5 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-4 --hidden_units 1024 --dropout_rate 0.5 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 2048 --dropout_rate 0.5 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 512 --dropout_rate 0.5 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 1024 --dropout_rate 0.3 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 1024 --dropout_rate 0.2 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 1024 --dropout_rate 0.1 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 1024 --dropout_rate 0.0 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 1024 --dropout_rate 0.5 --batch_size 256 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 1024 --dropout_rate 0.5 --batch_size 128 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 1024 --dropout_rate 0.5 --batch_size 64 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
hd run -n "Sound Classifier" python pytorch/main.py --balance_type 'balance_in_batch' --model_type 'decision_level_multi_attention' --learning_rate 1e-3 --hidden_units 256 --dropout_rate 0.5 --batch_size 500 --data_dir ./packed_features --workspace ./pub_audioset_classification --model_type='decision_level_multi_attention' train
